jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      env:
        RELEASE_VERSION: ${{github.ref}}
      id: create_release_file
      name: Create Release File To Upload
      run: 'git clone https://github.com/riskscanner/riskscanner-installer.git --depth=1

        cd riskscanner-installer

        rm -rf hudson.* .travis.yml .git .github

        chmod +x rsctl.sh

        cd ..

        version=`echo ${RELEASE_VERSION##*/}`

        filename=riskscanner-installer-$version

        mv riskscanner-installer $filename

        echo $version > $filename/config_init/conf/version

        sed -i "s@VERSION=.*@VERSION=${version}@g" $filename/static.env

        sed -i "s@Version=.*@Version=${version}@g" $filename/quick_start.sh

        tar -czvf $filename.tar.gz $filename

        echo "::set-output name=VERSION::$(echo $version)"

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: create_release
      name: Create Release
      uses: actions/create-release@v1
      with:
        body: "# \u5FEB\u901F\u5F00\u59CB\n\u4EC5\u9700\u4E24\u6B65\u5FEB\u901F\u5B89\
          \u88C5 RiskScanner\uFF1A\n  1.  \u51C6\u5907\u4E00\u53F0\u4E0D\u5C0F\u4E8E\
          \ 4 G\u5185\u5B58\u7684 64\u4F4D Linux \u4E3B\u673A\uFF1B\n  2.  \u4EE5\
          \ root \u7528\u6237\u6267\u884C\u5982\u4E0B\u547D\u4EE4\u4E00\u952E\u5B89\
          \u88C5 RiskScanner\u3002\n```sh\n  curl -sSL https://github.com/riskscanner/riskscanner/releases/latest/download/quick_start.sh\
          \ | bash\n```\n\u5982\u679C\u60A8\u5DF2\u7ECF\u90E8\u7F72\u65E7\u7248\u672C\
          \uFF0C\u53EF\u901A\u8FC7\u5982\u4E0B\u547D\u4EE4\u4E00\u952E\u5347\u7EA7\
          \u81F3\u6700\u65B0\u7248\u672C:\n```sh\n  # \u5347\u7EA7\n  ./rsctl.sh check_update\n\
          ```\n# \u4EA7\u54C1\u6587\u6863\n\u70B9\u51FB [\u5B8C\u6574\u6587\u6863\
          ](https://docs.riskscanner.io/) \u67E5\u770B\u5B8C\u6574\u7684\u5B89\u88C5\
          \u548C\u4F7F\u7528\u6587\u6863\n"
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: upload-release-asset
      name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: application/zip
        asset_name: riskscanner-installer-${{ steps.create_release_file.outputs.VERSION
          }}.tar.gz
        asset_path: ./riskscanner-installer-${{ steps.create_release_file.outputs.VERSION
          }}.tar.gz
        upload_url: ${{ steps.create_release.outputs.upload_url }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: upload-release-quick-start-shell
      name: Upload Quick Start Script
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: application/text
        asset_name: quick_start.sh
        asset_path: ./riskscanner-installer-${{ steps.create_release_file.outputs.VERSION
          }}/quick_start.sh
        upload_url: ${{ steps.create_release.outputs.upload_url }}
name: Create Release And Upload assets
on:
  repository_dispatch:
    types: trigger-ga___release.yml
